// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

//register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';

// facebook login
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_RESPONSE = 'FACEBOOK_LOGIN_RESPONSE';

// google login
export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';
export const GOOGLE_LOGIN_RESPONSE = 'GOOGLE_LOGIN_RESPONSE';

//loaders
export const LOADING_ENABLE_LOADER = 'LOADING_ENABLE_LOADER';
export const LOADING_DISABLE_LOADER = 'LOADING_DISABLE_LOADER';

//TOAST
export const ENABLE_SNACKBAR = 'ENABLE_SNACKBAR';
export const DISABLE_SNACKBAR = 'DISABLE_SNACKBAR';

// logout
export const LOGOUT = 'LOG_OUT';
