require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Convert all permission pods into static libraries
# pre_install do |installer|
#   installer.pod_targets.each do |pod|
#     if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
#       def pod.build_type;
#         # Uncomment one line depending on your CocoaPods version
#         Pod::BuildType.static_library # >= 1.9
#         #Pod::Target::BuildType.static_library # < 1.9
#       end
#     end
#   end
# end

target 'boilerplate' do
  config = use_native_modules!
  # inherit! :complete
  use_react_native!(:path => config["reactNativePath"])

  # $RNFirebaseAsStaticFramework = true

  ## Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  target 'boilerplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'boilerplate-tvOS' do
  # Pods for boilerplate-tvOS

  target 'boilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
