// Facebook Login
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST'
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS'
export const FACEBOOK_LOGIN_ERROR = 'FACEBOOK_LOGIN_ERROR'

// Google Login
export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR'

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
